spring.application.name=clientGrantTypeDemo

server.port=8081

#here we mention the client details after registring this client in keyclock
spring.security.oauth2.client.registration.backend-b.provider=keycloak
spring.security.oauth2.client.registration.backend-b.client-id=eazybankapi
spring.security.oauth2.client.registration.backend-b.client-secret=FqYs56AsjivTKOP1dhAE9dKPlP2VzLHf7yUQg20ST4jsHOIIw8arq3VoQxFNN3UlEmbyAjYHcnuQnauufzxbZG
spring.security.oauth2.client.registration.backend-b.authorization-grant-type=client_credentials

spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:8180/realms/eazybankdev/protocol/openid-connect/token