#when defining properties it is better we use format ${"ENV":here the value}
#here env can be anything variable name

spring.application.name=springsecsection1

spring.datasource.url=jdbc:mysql://localhost:3307/employee_directory

#we can give like below but then when we push into git the database usename and password will be seen to all so just use the line below the next line and mention the value in a env file
#spring.datasource.username=${DB_USERNAME:root}
spring.datasource.username=${DB_USERNAME}

#spring.datasource.password=${DB_PASSWORD:Kaetr2Cqnv1@1}
spring.datasource.password=${DB_PASSWORD}

logging.level.org.springframework.security=DEBUG