spring.application.name=springOAUTH2DemoUsingSocialLogin
spring.security.user.name=${SECURITY_USERNAME:root}
spring.security.user.password=${SECURITY_PASSWORD:Test@123}
logging.level.org.springframework.security=TRACE
