spring.application.name=springOAUTH2DemoUsingSocialLogin
spring.security.user.name=${SECURITY_USERNAME:root}
spring.security.user.password=${SECURITY_PASSWORD:Test@123}
logging.level.org.springframework.security=TRACE

#Way 2 to use sso
spring.security.oauth2.client.registration.github.client-id=Ov23lixMy6bfslEqKw8D
spring.security.oauth2.client.registration.github.client-secret=831747848cd15ca9518096e322efa01d8308fca2

spring.security.oauth2.client.registration.facebook.client-id=1989988658346097
spring.security.oauth2.client.registration.facebook.client-secret=1dc11b198c88b841313346608a65d927
